# Dockerfile.streamlit
FROM python:3.11-slim

WORKDIR /app

COPY Pipfile* /app/
RUN pip install pipenv && pipenv install --system --deploy

COPY . /app

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_cli.py", "--server.port=8501", "--server.address=0.0.0.0"]
